export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const FETCH_RESULT_LOADING = "FETCH_RESULT_LOADING";
export const FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";
export const FETCH_RESULT_ERROR = "FETCH_RESULT_ERROR";